version: '3.1'
volumes:
  io:
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  report-builder:
    image: kimvanwyk/ndlc_finance_report
    restart: always
    ports:
      - 5001:5001/udp
    volumes:
      - io:/io
    environment:
      - MONGODB_HOST=mongo
  flask:
    image: kimvanwyk/ndlc_finance_flask
    restart: always
    ports:
      - 5000:80
    environment:
      - MONGODB_HOST=mongo
      - REPORT_HOST=report-builder
    volumes:
      - io:/io
